## __Polarsの使い方__

- Github: https://github.com/pola-rs/polars

- 公式リファレンス: https://pola-rs.github.io/polars-book/user-guide/

- 参考記事
    - https://qiita.com/nkay/items/9cfb2776156dc7e054c8

    - https://qiita.com/_jinta/items/fac13f09e8e8a5769b79

- 100本ノック

    - 前編: https://qiita.com/_jinta/items/28442d25bba067c13bb7

    - 後編: https://qiita.com/_jinta/items/394b1682893e5991d592

In [1]:
!pip install polars | tail -n 1

Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from polars) (4.4.0)

In [2]:
import polars as pl

In [3]:
# csvファイルの読み込み
# indexが存在しない
df = pl.read_csv("sample_data/california_housing_train.csv")
df

shape: (17000, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [4]:
# データ型
type(df)

polars.internals.dataframe.frame.DataFrame

In [5]:
# pandasに変換
df.to_pandas()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [6]:
# numpyに変換
df.to_numpy()

array([[-1.1431e+02,  3.4190e+01,  1.5000e+01, ...,  4.7200e+02,
         1.4936e+00,  6.6900e+04],
       [-1.1447e+02,  3.4400e+01,  1.9000e+01, ...,  4.6300e+02,
         1.8200e+00,  8.0100e+04],
       [-1.1456e+02,  3.3690e+01,  1.7000e+01, ...,  1.1700e+02,
         1.6509e+00,  8.5700e+04],
       ...,
       [-1.2430e+02,  4.1840e+01,  1.7000e+01, ...,  4.5600e+02,
         3.0313e+00,  1.0360e+05],
       [-1.2430e+02,  4.1800e+01,  1.9000e+01, ...,  4.7800e+02,
         1.9797e+00,  8.5800e+04],
       [-1.2435e+02,  4.0540e+01,  5.2000e+01, ...,  2.7000e+02,
         3.0147e+00,  9.4600e+04]])

In [7]:
# print関数で先頭と末尾の5行を表示できる
print(df)

shape: (17000, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [8]:
# glimpse「垣間見る」
# 文字列で先頭10行を表示
print(df.glimpse())

Rows: 17000
Columns: 9
$ longitude          <f64> -114.31, -114.47, -114.56, -114.57, -114.57, -114.58, -114.58, -114.59, -114.59, -114.6
$ latitude           <f64> 34.19, 34.4, 33.69, 33.64, 33.57, 33.63, 33.61, 34.83, 33.61, 34.83
$ housing_median_age <f64> 15.0, 19.0, 17.0, 14.0, 20.0, 29.0, 25.0, 41.0, 34.0, 46.0
$ total_rooms        <f64> 5612.0, 7650.0, 720.0, 1501.0, 1454.0, 1387.0, 2907.0, 812.0, 4789.0, 1497.0
$ total_bedrooms     <f64> 1283.0, 1901.0, 174.0, 337.0, 326.0, 236.0, 680.0, 168.0, 1175.0, 309.0
$ population         <f64> 1015.0, 1129.0, 333.0, 515.0, 624.0, 671.0, 1841.0, 375.0, 3134.0, 787.0
$ households         <f64> 472.0, 463.0, 117.0, 226.0, 262.0, 239.0, 633.0, 158.0, 1056.0, 271.0
$ median_income      <f64> 1.4936, 1.82, 1.6509, 3.1917, 1.925, 3.3438, 2.6768, 1.7083, 2.1782, 2.1908
$ median_house_value <f64> 66900.0, 80100.0, 85700.0, 73400.0, 65500.0, 74000.0, 82400.0, 48500.0, 58400.0, 48100.0

In [9]:
# サイズ
df.shape

(17000, 9)

In [10]:
# 縦
df.height

17000

In [11]:
# 横
df.width

9

In [12]:
# 基本統計量
df.describe()

shape: (7, 10)
┌──────────┬─────────┬──────────┬────────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ describe ┆ longitu ┆ latitude ┆ housing_me ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ ---      ┆ de      ┆ ---      ┆ dian_age   ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ str      ┆ ---     ┆ f64      ┆ ---        ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│          ┆ f64     ┆          ┆ f64        ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞══════════╪═════════╪══════════╪════════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ count    ┆ 17000.0 ┆ 17000.0  ┆ 17000.0    ┆ ... ┆ 17000.0  ┆ 17000.0  ┆ 17000.0    ┆ 17000.0    │
│ null_cou ┆ 0.0     ┆ 0.0      ┆ 0.0        ┆ ... ┆ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0        │
│ nt       ┆         ┆          ┆            ┆     ┆          ┆          ┆            ┆            │
│ mean     ┆ -119.56 ┆ 35.62522 ┆ 28.589353  ┆ ... ┆ 1429.573 ┆ 501.2219 ┆ 3.883578   ┆ 207300.912 │
│          ┆ 2108    ┆ 5        ┆            ┆     ┆ 941      ┆ 41       ┆            ┆ 353        │
│ std      ┆ 2.00516 ┆ 2.13734  ┆ 12.586937  ┆ ... ┆ 1147.852 ┆ 384.5208 ┆ 1.908157   ┆ 115983.764 │
│          ┆ 6       ┆          ┆            ┆     ┆ 959      ┆ 41       ┆            ┆ 387        │
│ min      ┆ -124.35 ┆ 32.54    ┆ 1.0        ┆ ... ┆ 3.0      ┆ 1.0      ┆ 0.4999     ┆ 14999.0    │
│ max      ┆ -114.31 ┆ 41.95    ┆ 52.0       ┆ ... ┆ 35682.0  ┆ 6082.0   ┆ 15.0001    ┆ 500001.0   │
│ median   ┆ -118.49 ┆ 34.25    ┆ 29.0       ┆ ... ┆ 1167.0   ┆ 409.0    ┆ 3.5446     ┆ 180400.0   │
└──────────┴─────────┴──────────┴────────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [13]:
# 1行選択
# indexが存在しないことに注意
df[0]

shape: (1, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [14]:
# スライス
df[1:4]

shape: (3, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [15]:
# 先頭の5行
df.head()

shape: (5, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ -114.57 ┆ 33.57    ┆ 20.0       ┆ 1454.0    ┆ ... ┆ 624.0    ┆ 262.0    ┆ 1.925      ┆ 65500.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [16]:
# 末尾の5行
df.tail()

shape: (5, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -124.26 ┆ 40.58    ┆ 52.0       ┆ 2217.0    ┆ ... ┆ 907.0    ┆ 369.0    ┆ 2.3571     ┆ 111400.0   │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [17]:
# DataFrameの作成①
pl.DataFrame([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

shape: (4, 2)
┌──────────┬──────────┐
│ column_0 ┆ column_1 │
│ ---      ┆ ---      │
│ i64      ┆ i64      │
╞══════════╪══════════╡
│ 1        ┆ 5        │
│ 2        ┆ 6        │
│ 3        ┆ 7        │
│ 4        ┆ 8        │
└──────────┴──────────┘

In [18]:
# DataFrameの作成②
pl.DataFrame({
    "整数": [1, 2, 3, 4],
    "ひらがな": ["あ", "い", "う", "え"]
})

shape: (4, 2)
┌──────┬────────────┐
│ 整数 ┆ ひらがな   │
│ ---  ┆ ---        │
│ i64  ┆ str        │
╞══════╪════════════╡
│ 1    ┆ あ         │
│ 2    ┆ い         │
│ 3    ┆ う         │
│ 4    ┆ え         │
└──────┴────────────┘

In [19]:
# 条件式
df.filter((pl.col("longitude") > -120) & (pl.col("latitude") < 35))

shape: (9218, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -119.88 ┆ 34.43    ┆ 14.0       ┆ 2472.0    ┆ ... ┆ 1292.0   ┆ 621.0    ┆ 3.3026     ┆ 229500.0   │
│ -119.89 ┆ 34.44    ┆ 25.0       ┆ 3160.0    ┆ ... ┆ 1514.0   ┆ 523.0    ┆ 5.0767     ┆ 271200.0   │
│ -119.91 ┆ 34.4     ┆ 24.0       ┆ 2001.0    ┆ ... ┆ 1170.0   ┆ 330.0    ┆ 6.0992     ┆ 268800.0   │
│ -119.92 ┆ 34.44    ┆ 17.0       ┆ 2143.0    ┆ ... ┆ 1073.0   ┆ 330.0    ┆ 6.0321     ┆ 402600.0   │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [20]:
# 列を選択
# 1列のみ選択してもDataFrameとなる
df.select(["longitude", "latitude"])

shape: (17000, 2)
┌───────────┬──────────┐
│ longitude ┆ latitude │
│ ---       ┆ ---      │
│ f64       ┆ f64      │
╞═══════════╪══════════╡
│ -114.31   ┆ 34.19    │
│ -114.47   ┆ 34.4     │
│ -114.56   ┆ 33.69    │
│ -114.57   ┆ 33.64    │
│ ...       ┆ ...      │
│ -124.27   ┆ 40.69    │
│ -124.3    ┆ 41.84    │
│ -124.3    ┆ 41.8     │
│ -124.35   ┆ 40.54    │
└───────────┴──────────┘

In [21]:
# エクスプレッションのリストを指定することも可能
# スカラー値はブロードキャストされる
# 列名は自動的に付与される
df.select([
    pl.col("longitude") * 2,
    pl.col("latitude").mean(), # スカラー値
    pl.col("housing_median_age") + pl.col("total_rooms"), # 列名に注意
])

shape: (17000, 3)
┌───────────┬───────────┬────────────────────┐
│ longitude ┆ latitude  ┆ housing_median_age │
│ ---       ┆ ---       ┆ ---                │
│ f64       ┆ f64       ┆ f64                │
╞═══════════╪═══════════╪════════════════════╡
│ -228.62   ┆ 35.625225 ┆ 5627.0             │
│ -228.94   ┆ 35.625225 ┆ 7669.0             │
│ -229.12   ┆ 35.625225 ┆ 737.0              │
│ -229.14   ┆ 35.625225 ┆ 1515.0             │
│ ...       ┆ ...       ┆ ...                │
│ -248.54   ┆ 35.625225 ┆ 2385.0             │
│ -248.6    ┆ 35.625225 ┆ 2694.0             │
│ -248.6    ┆ 35.625225 ┆ 2691.0             │
│ -248.7    ┆ 35.625225 ┆ 1872.0             │
└───────────┴───────────┴────────────────────┘

In [22]:
# 列を選択
# 1列のみ選択するとSeriesとなる
df.get_column("longitude")

shape: (17000,)
Series: 'longitude' [f64]
[
	-114.31
	-114.47
	-114.56
	-114.57
	-114.57
	-114.58
	-114.58
	-114.59
	-114.59
	-114.6
	-114.6
	-114.6
	...
	-124.21
	-124.21
	-124.21
	-124.22
	-124.23
	-124.23
	-124.23
	-124.25
	-124.26
	-124.27
	-124.3
	-124.3
	-124.35
]

In [23]:
# 重複行の削除
# pandasのdrop_duplicates()と同じ
df.unique()

shape: (17000, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [24]:
# データ型で検索
df.select(pl.col(pl.Float64))

shape: (17000, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [25]:
# 全ての列を選択
# pl.col("*")も可
df.select(pl.all())

shape: (17000, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [26]:
# 列を除外して取得
df.select(pl.exclude("longitude"))

shape: (17000, 8)
┌──────────┬────────────┬───────────┬────────────┬──────────┬────────────┬────────────┬────────────┐
│ latitude ┆ housing_me ┆ total_roo ┆ total_bedr ┆ populati ┆ households ┆ median_inc ┆ median_hou │
│ ---      ┆ dian_age   ┆ ms        ┆ ooms       ┆ on       ┆ ---        ┆ ome        ┆ se_value   │
│ f64      ┆ ---        ┆ ---       ┆ ---        ┆ ---      ┆ f64        ┆ ---        ┆ ---        │
│          ┆ f64        ┆ f64       ┆ f64        ┆ f64      ┆            ┆ f64        ┆ f64        │
╞══════════╪════════════╪═══════════╪════════════╪══════════╪════════════╪════════════╪════════════╡
│ 34.19    ┆ 15.0       ┆ 5612.0    ┆ 1283.0     ┆ 1015.0   ┆ 472.0      ┆ 1.4936     ┆ 66900.0    │
│ 34.4     ┆ 19.0       ┆ 7650.0    ┆ 1901.0     ┆ 1129.0   ┆ 463.0      ┆ 1.82       ┆ 80100.0    │
│ 33.69    ┆ 17.0       ┆ 720.0     ┆ 174.0      ┆ 333.0    ┆ 117.0      ┆ 1.6509     ┆ 85700.0    │
│ 33.64    ┆ 14.0       ┆ 1501.0    ┆ 337.0      ┆ 515.0    ┆ 226.0      ┆ 3.1917     ┆ 73400.0    │
│ ...      ┆ ...        ┆ ...       ┆ ...        ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 40.69    ┆ 36.0       ┆ 2349.0    ┆ 528.0      ┆ 1194.0   ┆ 465.0      ┆ 2.5179     ┆ 79000.0    │
│ 41.84    ┆ 17.0       ┆ 2677.0    ┆ 531.0      ┆ 1244.0   ┆ 456.0      ┆ 3.0313     ┆ 103600.0   │
│ 41.8     ┆ 19.0       ┆ 2672.0    ┆ 552.0      ┆ 1298.0   ┆ 478.0      ┆ 1.9797     ┆ 85800.0    │
│ 40.54    ┆ 52.0       ┆ 1820.0    ┆ 300.0      ┆ 806.0    ┆ 270.0      ┆ 3.0147     ┆ 94600.0    │
└──────────┴────────────┴───────────┴────────────┴──────────┴────────────┴────────────┴────────────┘

In [27]:
# Seriesのリストに変換
df.get_columns()

[shape: (17000,)
 Series: 'longitude' [f64]
 [
 	-114.31
 	-114.47
 	-114.56
 	-114.57
 	-114.57
 	-114.58
 	-114.58
 	-114.59
 	-114.59
 	-114.6
 	-114.6
 	-114.6
 	...
 	-124.21
 	-124.21
 	-124.21
 	-124.22
 	-124.23
 	-124.23
 	-124.23
 	-124.25
 	-124.26
 	-124.27
 	-124.3
 	-124.3
 	-124.35
 ], shape: (17000,)
 Series: 'latitude' [f64]
 [
 	34.19
 	34.4
 	33.69
 	33.64
 	33.57
 	33.63
 	33.61
 	34.83
 	33.61
 	34.83
 	33.62
 	33.6
 	...
 	41.77
 	41.75
 	40.75
 	41.73
 	41.75
 	40.81
 	40.54
 	40.28
 	40.58
 	40.69
 	41.84
 	41.8
 	40.54
 ], shape: (17000,)
 Series: 'housing_median_age' [f64]
 [
 	15.0
 	19.0
 	17.0
 	14.0
 	20.0
 	29.0
 	25.0
 	41.0
 	34.0
 	46.0
 	16.0
 	21.0
 	...
 	17.0
 	20.0
 	32.0
 	28.0
 	11.0
 	52.0
 	52.0
 	32.0
 	52.0
 	36.0
 	17.0
 	19.0
 	52.0
 ], shape: (17000,)
 Series: 'total_rooms' [f64]
 [
 	5612.0
 	7650.0
 	720.0
 	1501.0
 	1454.0
 	1387.0
 	2907.0
 	812.0
 	4789.0
 	1497.0
 	3741.0
 	1988.0
 	...
 	3461.0
 	3810.0
 	1218.0
 	3003.0
 	3159.0
 	1112.0
 	2694.0
 	1430.0
 	2217.0
 	2349.0
 	2677.0
 	2672.0
 	1820.0
 ], shape: (17000,)
 Series: 'total_bedrooms' [f64]
 [
 	1283.0
 	1901.0
 	174.0
 	337.0
 	326.0
 	236.0
 	680.0
 	168.0
 	1175.0
 	309.0
 	801.0
 	483.0
 	...
 	722.0
 	787.0
 	331.0
 	699.0
 	616.0
 	209.0
 	453.0
 	419.0
 	394.0
 	528.0
 	531.0
 	552.0
 	300.0
 ], shape: (17000,)
 Series: 'population' [f64]
 [
 	1015.0
 	1129.0
 	333.0
 	515.0
 	624.0
 	671.0
 	1841.0
 	375.0
 	3134.0
 	787.0
 	2434.0
 	1182.0
 	...
 	1947.0
 	1993.0
 	620.0
 	1530.0
 	1343.0
 	544.0
 	1152.0
 	434.0
 	907.0
 	1194.0
 	1244.0
 	1298.0
 	806.0
 ], shape: (17000,)
 Series: 'households' [f64]
 [
 	472.0
 	463.0
 	117.0
 	226.0
 	262.0
 	239.0
 	633.0
 	158.0
 	1056.0
 	271.0
 	824.0
 	437.0
 	...
 	647.0
 	721.0
 	268.0
 	653.0
 	479.0
 	172.0
 	435.0
 	187.0
 	369.0
 	465.0
 	456.0
 	478.0
 	270.0
 ], shape: (17000,)
 Series: 'median_income' [f64]
 [
 	1.4936
 	1.82
 	1.6509
 	3.1917
 	1.925
 	3.3438
 	2.6768
 	1.7083
 	2.1782
 	2.1908
 	2.6797
 	1.625
 	...
 	2.5795
 	2.0074
 	1.6528
 	1.7038
 	2.4805
 	3.3462
 	3.0806
 	1.9417
 	2.3571
 	2.5179
 	3.0313
 	1.9797
 	3.0147
 ], shape: (17000,)
 Series: 'median_house_value' [f64]
 [
 	66900.0
 	80100.0
 	85700.0
 	73400.0
 	65500.0
 	74000.0
 	82400.0
 	48500.0
 	58400.0
 	48100.0
 	86500.0
 	62000.0
 	...
 	68400.0
 	66900.0
 	58100.0
 	78300.0
 	73200.0
 	50800.0
 	106700.0
 	76100.0
 	111400.0
 	79000.0
 	103600.0
 	85800.0
 	94600.0
 ]]

In [28]:
# その列が何番目の列か
df.find_idx_by_name("latitude")

1

In [29]:
# 列の追加(更新)①
# 列名を変更しない場合は列が上書きされる
# aliasで列名を変更
df.with_columns(
    (pl.col("longitude") * 2).alias("longitude2")
)

shape: (17000, 10)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬────────────┬────────────┬──────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ househol ┆ median_inc ┆ median_hou ┆ longitud │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ ds       ┆ ome        ┆ se_value   ┆ e2       │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---        ┆ ---        ┆ ---      │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64        ┆ f64        ┆ f64      │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪════════════╪════════════╪══════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 472.0    ┆ 1.4936     ┆ 66900.0    ┆ -228.62  │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 463.0    ┆ 1.82       ┆ 80100.0    ┆ -228.94  │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 117.0    ┆ 1.6509     ┆ 85700.0    ┆ -229.12  │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 226.0    ┆ 3.1917     ┆ 73400.0    ┆ -229.14  │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...      │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 465.0    ┆ 2.5179     ┆ 79000.0    ┆ -248.54  │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 456.0    ┆ 3.0313     ┆ 103600.0   ┆ -248.6   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 478.0    ┆ 1.9797     ┆ 85800.0    ┆ -248.6   │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 270.0    ┆ 3.0147     ┆ 94600.0    ┆ -248.7   │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴────────────┴────────────┴──────────┘

In [30]:
# 列の追加(更新)②
# キーワード引数でも指定できる
df.with_columns(
    longitude_mean=pl.mean("longitude"),
    longitude_max=pl.max("longitude"),
)

shape: (17000, 11)
┌─────────┬──────────┬────────────┬───────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ median_inc ┆ median_hou ┆ longitude_ ┆ longitude_ │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ ome        ┆ se_value   ┆ mean       ┆ max        │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1.4936     ┆ 66900.0    ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1.82       ┆ 80100.0    ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 1.6509     ┆ 85700.0    ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 3.1917     ┆ 73400.0    ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...        ┆ ...        ┆ ...        ┆ ...        │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 2.5179     ┆ 79000.0    ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 3.0313     ┆ 103600.0   ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1.9797     ┆ 85800.0    ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 3.0147     ┆ 94600.0    ┆ -119.56210 ┆ -114.31    │
│         ┆          ┆            ┆           ┆     ┆            ┆            ┆ 8          ┆            │
└─────────┴──────────┴────────────┴───────────┴─────┴────────────┴────────────┴────────────┴────────────┘

In [31]:
# 列の追加③
# selectを下のように使えば列を追加できる
df.select([
    pl.col("*"), # 全ての列
    pl.lit(0).alias("zero"), # 追加する列
])

shape: (17000, 10)
┌───────────┬──────────┬────────────┬───────────┬─────┬──────────┬────────────┬────────────┬──────┐
│ longitude ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ househol ┆ median_inc ┆ median_hou ┆ zero │
│ ---       ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ ds       ┆ ome        ┆ se_value   ┆ ---  │
│ f64       ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---        ┆ ---        ┆ i32  │
│           ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64        ┆ f64        ┆      │
╞═══════════╪══════════╪════════════╪═══════════╪═════╪══════════╪════════════╪════════════╪══════╡
│ -114.31   ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 472.0    ┆ 1.4936     ┆ 66900.0    ┆ 0    │
│ -114.47   ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 463.0    ┆ 1.82       ┆ 80100.0    ┆ 0    │
│ -114.56   ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 117.0    ┆ 1.6509     ┆ 85700.0    ┆ 0    │
│ -114.57   ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 226.0    ┆ 3.1917     ┆ 73400.0    ┆ 0    │
│ ...       ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...  │
│ -124.27   ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 465.0    ┆ 2.5179     ┆ 79000.0    ┆ 0    │
│ -124.3    ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 456.0    ┆ 3.0313     ┆ 103600.0   ┆ 0    │
│ -124.3    ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 478.0    ┆ 1.9797     ┆ 85800.0    ┆ 0    │
│ -124.35   ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 270.0    ┆ 3.0147     ┆ 94600.0    ┆ 0    │
└───────────┴──────────┴────────────┴───────────┴─────┴──────────┴────────────┴────────────┴──────┘

In [32]:
# 左端に0始まりの整数列「row_nr」を作成
# indexのような役割を果たせる
df.with_row_count()

shape: (17000, 10)
┌────────┬───────────┬──────────┬────────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ row_nr ┆ longitude ┆ latitude ┆ housing_me ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ ---    ┆ ---       ┆ ---      ┆ dian_age   ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ u32    ┆ f64       ┆ f64      ┆ ---        ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│        ┆           ┆          ┆ f64        ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞════════╪═══════════╪══════════╪════════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ 0      ┆ -114.31   ┆ 34.19    ┆ 15.0       ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ 1      ┆ -114.47   ┆ 34.4     ┆ 19.0       ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ 2      ┆ -114.56   ┆ 33.69    ┆ 17.0       ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ 3      ┆ -114.57   ┆ 33.64    ┆ 14.0       ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...    ┆ ...       ┆ ...      ┆ ...        ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ 16996  ┆ -124.27   ┆ 40.69    ┆ 36.0       ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ 16997  ┆ -124.3    ┆ 41.84    ┆ 17.0       ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ 16998  ┆ -124.3    ┆ 41.8     ┆ 19.0       ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ 16999  ┆ -124.35   ┆ 40.54    ┆ 52.0       ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└────────┴───────────┴──────────┴────────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [33]:
# ソート①
# エクスプレッション
df.select(pl.col("longitude").sort())

shape: (17000, 1)
┌───────────┐
│ longitude │
│ ---       │
│ f64       │
╞═══════════╡
│ -124.35   │
│ -124.3    │
│ -124.3    │
│ -124.27   │
│ ...       │
│ -114.57   │
│ -114.56   │
│ -114.47   │
│ -114.31   │
└───────────┘

In [34]:
# sum(行方向)
df.select(pl.sum(["longitude", "latitude"]))

shape: (17000, 1)
┌────────┐
│ sum    │
│ ---    │
│ f64    │
╞════════╡
│ -80.12 │
│ -80.07 │
│ -80.87 │
│ -80.93 │
│ ...    │
│ -83.58 │
│ -82.46 │
│ -82.5  │
│ -83.81 │
└────────┘

In [35]:
# sum(列方向)
df.select(pl.col(["longitude", "latitude"]).sum())

shape: (1, 2)
┌───────────┬───────────┐
│ longitude ┆ latitude  │
│ ---       ┆ ---       │
│ f64       ┆ f64       │
╞═══════════╪═══════════╡
│ -2.0326e6 ┆ 605628.82 │
└───────────┴───────────┘

In [36]:
df.select([
    pl.count("longitude").alias("count"),
    pl.n_unique("longitude").alias("n_unique"),
    pl.max("longitude").alias("max"),
    pl.min("longitude").alias("min"),
    pl.mean("longitude").alias("mean"),
    pl.median("longitude").alias("median"),
    pl.std("longitude").alias("std"),
    pl.var("longitude").alias("var"),
])

shape: (1, 8)
┌───────┬──────────┬─────────┬─────────┬─────────────┬─────────┬──────────┬──────────┐
│ count ┆ n_unique ┆ max     ┆ min     ┆ mean        ┆ median  ┆ std      ┆ var      │
│ ---   ┆ ---      ┆ ---     ┆ ---     ┆ ---         ┆ ---     ┆ ---      ┆ ---      │
│ u32   ┆ u32      ┆ f64     ┆ f64     ┆ f64         ┆ f64     ┆ f64      ┆ f64      │
╞═══════╪══════════╪═════════╪═════════╪═════════════╪═════════╪══════════╪══════════╡
│ 17000 ┆ 827      ┆ -114.31 ┆ -124.35 ┆ -119.562108 ┆ -118.49 ┆ 2.005166 ┆ 4.020692 │
└───────┴──────────┴─────────┴─────────┴─────────────┴─────────┴──────────┴──────────┘

In [37]:
# groupbyはoverで書ける
df.select(pl.col("latitude").sum().over("longitude"))

shape: (17000, 1)
┌──────────┐
│ latitude │
│ ---      │
│ f64      │
╞══════════╡
│ 34.19    │
│ 34.4     │
│ 33.69    │
│ 67.21    │
│ ...      │
│ 40.69    │
│ 83.64    │
│ 83.64    │
│ 40.54    │
└──────────┘

In [38]:
# 条件分岐
# when→then→otherwise
df.select(
    pl.when(pl.col("longitude") > -120)
    .then("a")
    .when(pl.col("longitude") > -115)
    .then("b")
    .otherwise("c")
)

shape: (17000, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ a       │
│ a       │
│ a       │
│ a       │
│ ...     │
│ c       │
│ c       │
│ c       │
│ c       │
└─────────┘

In [39]:
# DataFrameの結合
a, b = df[:10], df[10:20]
pl.concat([a, b])

shape: (20, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -114.65 ┆ 33.6     ┆ 28.0       ┆ 1678.0    ┆ ... ┆ 666.0    ┆ 256.0    ┆ 2.9653     ┆ 94900.0    │
│ -114.65 ┆ 32.79    ┆ 21.0       ┆ 44.0      ┆ ... ┆ 64.0     ┆ 27.0     ┆ 0.8571     ┆ 25000.0    │
│ -114.66 ┆ 32.74    ┆ 17.0       ┆ 1388.0    ┆ ... ┆ 775.0    ┆ 320.0    ┆ 1.2049     ┆ 44000.0    │
│ -114.67 ┆ 33.92    ┆ 17.0       ┆ 97.0      ┆ ... ┆ 29.0     ┆ 15.0     ┆ 1.2656     ┆ 27500.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [40]:
# groupby
# 行はランダムにソートされる
df.groupby("longitude").mean()

shape: (827, 9)
┌─────────┬─────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitud ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ e       ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ ---     ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆ f64     ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪═════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -115.5  ┆ 32.7    ┆ 22.0       ┆ 2040.0    ┆ ... ┆ 2027.0   ┆ 487.6666 ┆ 2.3938     ┆ 102133.333 │
│         ┆         ┆            ┆           ┆     ┆          ┆ 67       ┆            ┆ 333        │
│ -116.0  ┆ 32.965  ┆ 21.0       ┆ 689.5     ┆ ... ┆ 205.0    ┆ 95.5     ┆ 1.34885    ┆ 47600.0    │
│ -116.25 ┆ 33.75   ┆ 20.666667  ┆ 940.66666 ┆ ... ┆ 596.3333 ┆ 208.0    ┆ 2.75       ┆ 70133.3333 │
│         ┆         ┆            ┆ 7         ┆     ┆ 33       ┆          ┆            ┆ 33         │
│ -116.5  ┆ 33.85   ┆ 15.4       ┆ 4353.2    ┆ ... ┆ 2022.6   ┆ 825.0    ┆ 2.52682    ┆ 128680.0   │
│ ...     ┆ ...     ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -119.26 ┆ 35.2044 ┆ 33.777778  ┆ 2149.5555 ┆ ... ┆ 1150.0   ┆ 412.5555 ┆ 3.202078   ┆ 199922.222 │
│         ┆ 44      ┆            ┆ 56        ┆     ┆          ┆ 56       ┆            ┆ 222        │
│ -119.51 ┆ 34.994  ┆ 22.6       ┆ 2064.6    ┆ ... ┆ 915.0    ┆ 340.4    ┆ 4.03594    ┆ 335180.2   │
│ -119.76 ┆ 36.66   ┆ 29.0       ┆ 3159.4285 ┆ ... ┆ 1925.571 ┆ 662.6190 ┆ 2.35661    ┆ 80271.4285 │
│         ┆         ┆            ┆ 71        ┆     ┆ 429      ┆ 48       ┆            ┆ 71         │
│ -120.01 ┆ 38.97   ┆ 23.166667  ┆ 1890.5    ┆ ... ┆ 619.0    ┆ 280.6666 ┆ 2.400817   ┆ 107233.333 │
│         ┆         ┆            ┆           ┆     ┆          ┆ 67       ┆            ┆ 333        │
└─────────┴─────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [41]:
# GroupByオブジェクトをイテレータとして使う
# group_name, group_dfが返る
grouped = df.groupby("longitude")

for group_name, group_df in grouped:
    print(group_name)
    print(group_df)
    break

-121.35
shape: (23, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -121.35 ┆ 38.72    ┆ 2.0        ┆ 21897.0   ┆ ... ┆ 8652.0   ┆ 2873.0   ┆ 4.5432     ┆ 151300.0   │
│ -121.35 ┆ 38.7     ┆ 5.0        ┆ 14414.0   ┆ ... ┆ 7608.0   ┆ 2832.0   ┆ 3.5802     ┆ 129600.0   │
│ -121.35 ┆ 38.68    ┆ 18.0       ┆ 7923.0    ┆ ... ┆ 3789.0   ┆ 1473.0   ┆ 3.5403     ┆ 98600.0    │
│ -121.35 ┆ 38.65    ┆ 20.0       ┆ 2498.0    ┆ ... ┆ 1185.0   ┆ 506.0    ┆ 3.2243     ┆ 107900.0   │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -121.35 ┆ 38.01    ┆ 15.0       ┆ 2682.0    ┆ ... ┆ 1520.0   ┆ 601.0    ┆ 3.5982     ┆ 94400.0    │
│ -121.35 ┆ 38.0     ┆ 22.0       ┆ 3564.0    ┆ ... ┆ 1539.0   ┆ 699.0    ┆ 3.675      ┆ 152400.0   │
│ -121.35 ┆ 37.97    ┆ 33.0       ┆ 3656.0    ┆ ... ┆ 1698.0   ┆ 671.0    ┆ 3.1406     ┆ 93900.0    │
│ -121.35 ┆ 37.96    ┆ 21.0       ┆ 1343.0    ┆ ... ┆ 462.0    ┆ 193.0    ┆ 5.8995     ┆ 189900.0   │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [42]:
# 欠損値補完
# nullとNanでそれぞれメソッドがある
# 平均値補完は"mean"
# 他にも"backward", "max", "zero"などがある

# df.fill_nan(0)
df.fill_null(0)

shape: (17000, 9)
┌─────────┬──────────┬────────────┬───────────┬─────┬──────────┬──────────┬────────────┬────────────┐
│ longitu ┆ latitude ┆ housing_me ┆ total_roo ┆ ... ┆ populati ┆ househol ┆ median_inc ┆ median_hou │
│ de      ┆ ---      ┆ dian_age   ┆ ms        ┆     ┆ on       ┆ ds       ┆ ome        ┆ se_value   │
│ ---     ┆ f64      ┆ ---        ┆ ---       ┆     ┆ ---      ┆ ---      ┆ ---        ┆ ---        │
│ f64     ┆          ┆ f64        ┆ f64       ┆     ┆ f64      ┆ f64      ┆ f64        ┆ f64        │
╞═════════╪══════════╪════════════╪═══════════╪═════╪══════════╪══════════╪════════════╪════════════╡
│ -114.31 ┆ 34.19    ┆ 15.0       ┆ 5612.0    ┆ ... ┆ 1015.0   ┆ 472.0    ┆ 1.4936     ┆ 66900.0    │
│ -114.47 ┆ 34.4     ┆ 19.0       ┆ 7650.0    ┆ ... ┆ 1129.0   ┆ 463.0    ┆ 1.82       ┆ 80100.0    │
│ -114.56 ┆ 33.69    ┆ 17.0       ┆ 720.0     ┆ ... ┆ 333.0    ┆ 117.0    ┆ 1.6509     ┆ 85700.0    │
│ -114.57 ┆ 33.64    ┆ 14.0       ┆ 1501.0    ┆ ... ┆ 515.0    ┆ 226.0    ┆ 3.1917     ┆ 73400.0    │
│ ...     ┆ ...      ┆ ...        ┆ ...       ┆ ... ┆ ...      ┆ ...      ┆ ...        ┆ ...        │
│ -124.27 ┆ 40.69    ┆ 36.0       ┆ 2349.0    ┆ ... ┆ 1194.0   ┆ 465.0    ┆ 2.5179     ┆ 79000.0    │
│ -124.3  ┆ 41.84    ┆ 17.0       ┆ 2677.0    ┆ ... ┆ 1244.0   ┆ 456.0    ┆ 3.0313     ┆ 103600.0   │
│ -124.3  ┆ 41.8     ┆ 19.0       ┆ 2672.0    ┆ ... ┆ 1298.0   ┆ 478.0    ┆ 1.9797     ┆ 85800.0    │
│ -124.35 ┆ 40.54    ┆ 52.0       ┆ 1820.0    ┆ ... ┆ 806.0    ┆ 270.0    ┆ 3.0147     ┆ 94600.0    │
└─────────┴──────────┴────────────┴───────────┴─────┴──────────┴──────────┴────────────┴────────────┘

In [43]:
# 文字列処理
# strアクセサ
text_df = pl.DataFrame({
    "number": ["one", "two", "three", "four"]
})

text_df

shape: (4, 1)
┌────────┐
│ number │
│ ---    │
│ str    │
╞════════╡
│ one    │
│ two    │
│ three  │
│ four   │
└────────┘

In [44]:
text_df.with_columns([
    pl.col("number").str.lengths().alias("length"), # 長さ(バイト数)
    pl.col("number").str.to_uppercase().alias("upper"), # 大文字
    pl.col("number").str.slice(1, 3).alias("slice"), # スライス
    pl.col("number").str.n_chars().alias("n_chars"), # 長さ(全角文字等を使う場合)
    pl.col("number").str.contains("o").alias("contain_o"), # 文字列を含むか
    pl.col("number").str.replace("o", "O").alias("replace"), # 置換
])

shape: (4, 7)
┌────────┬────────┬───────┬───────┬─────────┬───────────┬─────────┐
│ number ┆ length ┆ upper ┆ slice ┆ n_chars ┆ contain_o ┆ replace │
│ ---    ┆ ---    ┆ ---   ┆ ---   ┆ ---     ┆ ---       ┆ ---     │
│ str    ┆ u32    ┆ str   ┆ str   ┆ u32     ┆ bool      ┆ str     │
╞════════╪════════╪═══════╪═══════╪═════════╪═══════════╪═════════╡
│ one    ┆ 3      ┆ ONE   ┆ ne    ┆ 3       ┆ true      ┆ One     │
│ two    ┆ 3      ┆ TWO   ┆ wo    ┆ 3       ┆ true      ┆ twO     │
│ three  ┆ 5      ┆ THREE ┆ hre   ┆ 5       ┆ false     ┆ three   │
│ four   ┆ 4      ┆ FOUR  ┆ our   ┆ 4       ┆ true      ┆ fOur    │
└────────┴────────┴───────┴───────┴─────────┴───────────┴─────────┘